name: Publish NuGet Packages

on:
  release:
    types: [published] # Triggers only when a new release is published

jobs:
  publish_nuget:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x" # Ensure this matches your project version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Pack the project
        run: dotnet pack --configuration Release --output ./nupkgs

      - name: Publish NuGet packages
        shell: pwsh
        run: |
          $nugetApiKey = $env:NUGET_API_KEY
          $nugetUrl = "https://api.nuget.org/v3/index.json"
          $packages = Get-ChildItem -Path ./nupkgs -Filter *.nupkg

          foreach ($pkg in $packages) {
              dotnet nuget push $pkg.FullName --api-key $nugetApiKey --source $nugetUrl --skip-duplicate
          }
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
